extend type Mutation {
  createScheduleRun(input: ScheduleRunInput! @spread): ScheduleRun
    @guard(with: ["api"])
    @create(model: "App\\Models\\ScheduleRun")

  updateScheduleRun(input: ScheduleRunUpdateInput! @spread): ScheduleRun
    @guard(with: ["api"])
    @update(model: "App\\Models\\ScheduleRun")

  deleteScheduleRun(id: ID!): ScheduleRun
    @guard(with: ["api"])
    @delete(model: "App\\Models\\ScheduleRun")

  generateSchedule(id: ID!): ScheduleRun
    @guard(with: ["api"])
    @field(resolver: "App\\GraphQL\\Mutations\\ScheduleRunMutation@generate")

  publishSchedule(id: ID!): ScheduleRun
    @guard(with: ["api"])
    @field(resolver: "App\\GraphQL\\Mutations\\ScheduleRunMutation@publish")

  archiveSchedule(id: ID!): ScheduleRun
    @guard(with: ["api"])
    @field(resolver: "App\\GraphQL\\Mutations\\ScheduleRunMutation@archive")
}