extend type Mutation {
  createReplacementRequest(input: ReplacementRequestInput! @spread): ReplacementRequest
    @guard(with: ["api"])
    @create(model: "App\\Models\\ReplacementRequest")

  updateReplacementRequest(input: ReplacementRequestUpdateInput! @spread): ReplacementRequest
    @guard(with: ["api"])
    @update(model: "App\\Models\\ReplacementRequest")

  createReplacementBid(input: ReplacementBidInput! @spread): ReplacementBid
    @guard(with: ["api"])
    @create(model: "App\\Models\\ReplacementBid")

  updateReplacementBid(input: ReplacementBidUpdateInput! @spread): ReplacementBid
    @guard(with: ["api"])
    @update(model: "App\\Models\\ReplacementBid")
}